name: open-emarsys

networks:
  oe:
    name: oe
    driver: bridge

volumes:
  pgdata:
  miniodata:
  natsdata:
  chdata:

include:
  - infra/postgres.yml
  - infra/redis.yml
  - infra/minio.yml
  - infra/mailpit.yml
  - infra/nats.yml
  - infra/clickhouse.yml
  - infra/temporal.yml
