#!/usr/bin/env node
// Scans apps/admin-web/src/nav/*.ts (excluding types.ts/index.ts) and writes
// the aggregated, gitignored src/nav/index.ts. Runs in predev/prebuild/pretest.
import { readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const navDir = path.resolve(__dirname, '../../apps/admin-web/src/nav');
const outFile = path.join(navDir, 'index.ts');

const featureFiles = readdirSync(navDir)
  .filter((file) => file.endsWith('.ts'))
  .filter((file) => file !== 'types.ts' && file !== 'index.ts')
  .sort();

const imports = featureFiles
  .map((file, i) => `import nav_${i} from './${file.replace(/\.ts$/, '')}';`)
  .join('\n');

const spreads = featureFiles.map((_, i) => `  ...nav_${i},`).join('\n');

const banner =
  '// AUTO-GENERATED by scripts/codegen/nav.mjs — do not edit.\n' +
  '// Regenerate with `node scripts/codegen/nav.mjs`.\n';

const content = `${banner}import type { NavItem } from './types';
${imports ? `${imports}\n` : ''}
export const navItems: NavItem[] = [
${spreads}
];
`;

writeFileSync(outFile, content);
console.log(
  `nav.mjs: wrote ${featureFiles.length} feature(s) to ${path.relative(process.cwd(), outFile)}`
);
